In [2]:
#task one

In [5]:
import os

# List all files in the current directory
print("📁 Files in current folder:")
print("="*50)
for file in os.listdir():
    print(f"  📄 {file}")

📁 Files in current folder:
==================================================
  📄 .ipynb_checkpoints
  📄 Dataset for Data Analytics - Sheet1.csv
  📄 task1.ipynb

In [6]:
import pandas as pd
import numpy as np

# Load the dataset (exact name from your folder)
df = pd.read_csv('Dataset for Data Analytics - Sheet1.csv')

print("✅ DATASET LOADED SUCCESSFULLY!")
print("="*50)
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")
print("\nFirst 5 rows:")
df.head()

✅ DATASET LOADED SUCCESSFULLY!
==================================================
Rows: 1200, Columns: 14

First 5 rows:

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [7]:
print("📊 COLUMN NAMES:")
print(df.columns.tolist())
print("\n" + "="*50)

print("📊 DATA TYPES:")
print(df.dtypes)
print("\n" + "="*50)

print("📊 BASIC INFO:")
df.info()
print("\n" + "="*50)

print("📊 STATISTICAL SUMMARY:")
df.describe()

📊 COLUMN NAMES:
['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice', 'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber', 'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice']

==================================================
📊 DATA TYPES:
OrderID             object
Date                object
CustomerID          object
Product             object
Quantity             int64
UnitPrice          float64
ShippingAddress     object
PaymentMethod       object
OrderStatus         object
TrackingNumber      object
ItemsInCart          int64
CouponCode          object
ReferralSource      object
TotalPrice         float64
dtype: object

==================================================
📊 BASIC INFO:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   object
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: float64(2), int64(2), object(10)
memory usage: 131.4+ KB

==================================================
📊 STATISTICAL SUMMARY:

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1200.000000  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750     5.485000  1053.968300
std       1.407557   197.177146     2.281983   819.856558
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   186.062500     4.000000   410.520000
50%       3.000000   364.210000     5.000000   823.615000
75%       4.000000   521.570000     7.000000  1578.475000
max       5.000000   699.930000    10.000000  3456.400000

In [8]:
print("🔍 DATA QUALITY AUDIT")
print("="*50)

# 1. Check for Missing Values
print("\n1️⃣ MISSING VALUES:")
missing = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100
missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Missing %': missing_percent.round(2)
})
print(missing_df[missing_df['Missing Count'] > 0])

# 2. Check for Duplicates
print("\n2️⃣ DUPLICATES:")
print(f"Duplicate rows: {df.duplicated().sum()}")

# Check if there's an ID column (common names)
id_columns = [col for col in df.columns if 'id' in col.lower() or 'ID' in col]
if id_columns:
    for id_col in id_columns:
        print(f"Duplicate values in '{id_col}': {df[id_col].duplicated().sum()}")
else:
    print("No ID column found - checking all columns for duplicates")

# 3. Check Data Types - find text columns with issues
print("\n3️⃣ TEXT COLUMN CLEANING NEEDED:")
text_cols = df.select_dtypes(include=['object']).columns
for col in text_cols:
    unique_vals = df[col].unique()
    print(f"\n'{col}' - {len(unique_vals)} unique values")
    print(f"Sample: {unique_vals[:5]}")
    
    # Check for whitespace issues
    has_spaces = df[col].str.contains(r'^\s+|\s+$', na=False).any()
    if has_spaces:
        print(f"⚠️  Has leading/trailing spaces!")

# 4. Check Date Columns
print("\n4️⃣ DATE COLUMNS:")
date_cols = [col for col in df.columns if 'date' in col.lower()]
if date_cols:
    for col in date_cols:
        print(f"\n'{col}' - Sample values: {df[col].head(3).tolist()}")
        # Try to convert to datetime to see if format is consistent
        try:
            pd.to_datetime(df[col])
            print(f"✅ '{col}' can be converted to datetime")
        except:
            print(f"⚠️ '{col}' has inconsistent date formats")
else:
    print("No columns with 'date' in name found")

print("\n" + "="*50)
print("📊 SUMMARY STATISTICS:")
print(f"Total rows: {len(df)}")
print(f"Total columns: {len(df.columns)}")
print(f"Total missing values: {df.isnull().sum().sum()}")

🔍 DATA QUALITY AUDIT
==================================================

1️⃣ MISSING VALUES:
            Missing Count  Missing %
CouponCode            309      25.75

2️⃣ DUPLICATES:
Duplicate rows: 0
Duplicate values in 'OrderID': 0
Duplicate values in 'CustomerID': 11

3️⃣ TEXT COLUMN CLEANING NEEDED:

'OrderID' - 1200 unique values
Sample: ['ORD200000' 'ORD200001' 'ORD200002' 'ORD200003' 'ORD200004']

'Date' - 671 unique values
Sample: ['2023-01-04' '2024-08-23' '2024-02-27' '2023-10-15' '2025-05-08']

'CustomerID' - 1189 unique values
Sample: ['C72649' 'C75739' 'C81728' 'C33540' 'C81840']

'Product' - 7 unique values
Sample: ['Monitor' 'Phone' 'Tablet' 'Chair' 'Printer']

'ShippingAddress' - 655 unique values
Sample: ['928 Main St' '823 Main St' '512 Main St' '275 Main St' '668 Main St']

'PaymentMethod' - 5 unique values
Sample: ['Debit Card' 'Online' 'Credit Card' 'Gift Card' 'Cash']

'OrderStatus' - 5 unique values
Sample: ['Shipped' 'Cancelled' 'Returned' 'Delivered' 'Pending']

'TrackingNumber' - 1200 unique values
Sample: ['TRK37947903' 'TRK91186779' 'TRK42903982' 'TRK62788070' 'TRK29241424']

'CouponCode' - 4 unique values
Sample: ['SAVE10' 'FREESHIP' nan 'WINTER15']

'ReferralSource' - 5 unique values
Sample: ['Instagram' 'Referral' 'Email' 'Facebook' 'Google']

4️⃣ DATE COLUMNS:

'Date' - Sample values: ['2023-01-04', '2024-08-23', '2024-02-27']
✅ 'Date' can be converted to datetime

==================================================
📊 SUMMARY STATISTICS:
Total rows: 1200
Total columns: 14
Total missing values: 309

In [11]:
# Create a working copy
df_clean = df.copy()
print("✅ Working copy created")
print(f"Original shape: {df.shape}")
print(f"Copy shape: {df_clean.shape}")

✅ Working copy created
Original shape: (1200, 14)
Copy shape: (1200, 14)

In [12]:
print("🔧 FIXING MISSING VALUES")
print("="*50)

# Fill CouponCode with 'No Coupon' - NEW SYNTAX
missing_before = df_clean['CouponCode'].isnull().sum()
df_clean['CouponCode'] = df_clean['CouponCode'].fillna('No Coupon')
missing_after = df_clean['CouponCode'].isnull().sum()
print(f"✅ CouponCode: {missing_before} → {missing_after} missing values filled with 'No Coupon'")

# Check if any other columns have missing values
total_missing = df_clean.isnull().sum().sum()
print(f"\n✅ Total missing values now: {total_missing}")

🔧 FIXING MISSING VALUES
==================================================
✅ CouponCode: 309 → 0 missing values filled with 'No Coupon'

✅ Total missing values now: 0

In [13]:
print("🔧 REMOVING DUPLICATES")
print("="*50)

# Remove duplicate CustomerIDs (keep first occurrence)
before = len(df_clean)
df_clean = df_clean.drop_duplicates(subset=['CustomerID'], keep='first')
after = len(df_clean)
removed = before - after
print(f"✅ Removed {removed} duplicate CustomerID rows")
print(f"Rows before: {before}, Rows after: {after}")

# Verify no duplicates remain
duplicate_check = df_clean['CustomerID'].duplicated().sum()
print(f"✅ Duplicate CustomerIDs remaining: {duplicate_check}")

🔧 REMOVING DUPLICATES
==================================================
✅ Removed 11 duplicate CustomerID rows
Rows before: 1200, Rows after: 1189
✅ Duplicate CustomerIDs remaining: 0

In [14]:
print("🔧 CLEANING TEXT COLUMNS")
print("="*50)

# Identify text columns (skip ID columns and dates)
text_cols = df_clean.select_dtypes(include=['object']).columns
skip_cols = ['OrderID', 'CustomerID', 'Date', 'TrackingNumber']  # Keep these as-is

for col in text_cols:
    if col not in skip_cols:
        # Remove leading/trailing spaces and convert to Proper Case - NEW SYNTAX
        df_clean[col] = df_clean[col].str.strip().str.title()
        print(f"✅ Cleaned '{col}'")

# Show sample of cleaned text
print("\n📊 Sample of cleaned text columns:")
for col in text_cols:
    if col not in skip_cols:
        print(f"\n{col}: {df_clean[col].unique()[:5]}")

🔧 CLEANING TEXT COLUMNS
==================================================
✅ Cleaned 'Product'
✅ Cleaned 'ShippingAddress'
✅ Cleaned 'PaymentMethod'
✅ Cleaned 'OrderStatus'
✅ Cleaned 'CouponCode'
✅ Cleaned 'ReferralSource'

📊 Sample of cleaned text columns:

Product: ['Monitor' 'Phone' 'Tablet' 'Chair' 'Printer']

ShippingAddress: ['928 Main St' '823 Main St' '512 Main St' '275 Main St' '668 Main St']

PaymentMethod: ['Debit Card' 'Online' 'Credit Card' 'Gift Card' 'Cash']

OrderStatus: ['Shipped' 'Cancelled' 'Returned' 'Delivered' 'Pending']

CouponCode: ['Save10' 'Freeship' 'No Coupon' 'Winter15']

ReferralSource: ['Instagram' 'Referral' 'Email' 'Facebook' 'Google']

In [15]:
print("🔧 CHECKING NUMERIC COLUMNS")
print("="*50)

# Find numeric columns
numeric_cols = df_clean.select_dtypes(include=[np.number]).columns.tolist()
print(f"Numeric columns found: {numeric_cols}")

# Round to 2 decimals - NEW SYNTAX
for col in numeric_cols:
    df_clean[col] = df_clean[col].round(2)
    print(f"✅ Rounded '{col}' to 2 decimal places")

# Show sample
if numeric_cols:
    print("\n📊 Sample of rounded numeric values:")
    print(df_clean[numeric_cols].head())

🔧 CHECKING NUMERIC COLUMNS
==================================================
Numeric columns found: ['Quantity', 'UnitPrice', 'ItemsInCart', 'TotalPrice']
✅ Rounded 'Quantity' to 2 decimal places
✅ Rounded 'UnitPrice' to 2 decimal places
✅ Rounded 'ItemsInCart' to 2 decimal places
✅ Rounded 'TotalPrice' to 2 decimal places

📊 Sample of rounded numeric values:
   Quantity  UnitPrice  ItemsInCart  TotalPrice
0         5     570.62            7     2853.10
1         2     151.35            3      302.70
2         5     550.68            8     2753.40
3         1     273.19            5      273.19
4         4     626.01            8     2504.04

In [16]:
print("🔧 VERIFYING DATE FORMATS")
print("="*50)

# Check if Date column is in YYYY-MM-DD format - NEW SYNTAX
try:
    # Convert to datetime to verify
    df_clean['Date'] = pd.to_datetime(df_clean['Date'])
    # Format as YYYY-MM-DD
    df_clean['Date'] = df_clean['Date'].dt.strftime('%Y-%m-%d')
    print("✅ Date column is in ISO 8601 format (YYYY-MM-DD)")
    print(f"Sample dates: {df_clean['Date'].head(3).tolist()}")
except Exception as e:
    print(f"⚠️ Issue with dates: {e}")

🔧 VERIFYING DATE FORMATS
==================================================
✅ Date column is in ISO 8601 format (YYYY-MM-DD)
Sample dates: ['2023-01-04', '2024-08-23', '2024-02-27']

In [17]:
print("="*60)
print("🔬 FINAL DATA QUALITY VALIDATION")
print("="*60)

# 1. Check missing values
missing = df_clean.isnull().sum().sum()
print(f"✅ Missing values: {missing} (Target: 0)")

# 2. Check duplicate CustomerIDs
dup_customers = df_clean['CustomerID'].duplicated().sum()
print(f"✅ Duplicate CustomerIDs: {dup_customers} (Target: 0)")

# 3. Check date format
try:
    pd.to_datetime(df_clean['Date'])
    print(f"✅ Date format: Valid ISO 8601 (YYYY-MM-DD)")
except:
    print(f"⚠️ Date format: Check required")

# 4. Check text columns for whitespace
text_cols = df_clean.select_dtypes(include=['object']).columns
has_whitespace = False
for col in text_cols:
    if df_clean[col].str.contains(r'^\s+|\s+$', na=False).any():
        has_whitespace = True
        print(f"⚠️ '{col}' has leading/trailing spaces")
if not has_whitespace:
    print(f"✅ No whitespace issues in text columns")

# 5. Final summary
print("\n" + "="*60)
print("🎉 DATA CLEANING COMPLETE!")
print("="*60)
print(f"📊 Final Dataset Shape: {df_clean.shape[0]} rows, {df_clean.shape[1]} columns")
print(f"📊 Total rows removed (duplicates): {removed}")
print(f"📊 Missing values handled: 309 in CouponCode")
print("\n✅ Dataset is now READY for analysis!")

============================================================
🔬 FINAL DATA QUALITY VALIDATION
============================================================
✅ Missing values: 0 (Target: 0)
✅ Duplicate CustomerIDs: 0 (Target: 0)
✅ Date format: Valid ISO 8601 (YYYY-MM-DD)
✅ No whitespace issues in text columns

============================================================
🎉 DATA CLEANING COMPLETE!
============================================================
📊 Final Dataset Shape: 1189 rows, 14 columns
📊 Total rows removed (duplicates): 11
📊 Missing values handled: 309 in CouponCode

✅ Dataset is now READY for analysis!

In [18]:
from datetime import datetime

# Save cleaned data
df_clean.to_csv('cleaned_dataset.csv', index=False)
print("✅ Saved as 'cleaned_dataset.csv'")

# Also save as Excel (easier for business users)
df_clean.to_excel('cleaned_dataset.xlsx', index=False)
print("✅ Saved as 'cleaned_dataset.xlsx'")

# Create Change Log (Required per project guidelines)
change_log = pd.DataFrame({
    'Change ID': ['CR001', 'CR002', 'CR003', 'CR004', 'CR005'],
    'Description': [
        'Filled missing values in CouponCode with "No Coupon"',
        'Removed duplicate CustomerID rows (kept first occurrence)',
        'Converted text columns to Proper Case and trimmed whitespace',
        'Verified Date column in YYYY-MM-DD format',
        'Rounded numeric columns to 2 decimal places'
    ],
    'Impact': [
        f'Handled 309 missing values',
        f'Removed {removed} duplicate customer records',
        'Standardized all text fields',
        'Ensured ISO 8601 compliance',
        'Improved numeric precision for analysis'
    ],
    'Status': ['Resolved', 'Resolved', 'Resolved', 'Resolved', 'Resolved']
})

# Save change log
change_log.to_csv('change_log.csv', index=False)
print("✅ Change log saved as 'change_log.csv'")

# Display the change log
print("\n📋 CHANGE LOG:")
print(change_log.to_string(index=False))

# Save with timestamp for backup
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
df_clean.to_csv(f'cleaned_dataset_{timestamp}.csv', index=False)
print(f"\n✅ Backup saved as 'cleaned_dataset_{timestamp}.csv'")

✅ Saved as 'cleaned_dataset.csv'
✅ Saved as 'cleaned_dataset.xlsx'
✅ Change log saved as 'change_log.csv'

📋 CHANGE LOG:
Change ID                                                  Description                                  Impact   Status
    CR001         Filled missing values in CouponCode with "No Coupon"              Handled 309 missing values Resolved
    CR002    Removed duplicate CustomerID rows (kept first occurrence)   Removed 11 duplicate customer records Resolved
    CR003 Converted text columns to Proper Case and trimmed whitespace            Standardized all text fields Resolved
    CR004                    Verified Date column in YYYY-MM-DD format             Ensured ISO 8601 compliance Resolved
    CR005                  Rounded numeric columns to 2 decimal places Improved numeric precision for analysis Resolved

✅ Backup saved as 'cleaned_dataset_20260712_084320.csv'

In [19]:
print("📊 EXPLORE YOUR CLEAN DATASET")
print("="*60)

print("\n1️⃣ FIRST 5 ROWS:")
df_clean.head()

print("\n2️⃣ DATASET INFO:")
df_clean.info()

print("\n3️⃣ UNIQUE VALUES IN KEY COLUMNS:")
print(f"Products: {df_clean['Product'].unique().tolist()}")
print(f"Payment Methods: {df_clean['PaymentMethod'].unique().tolist()}")
print(f"Order Statuses: {df_clean['OrderStatus'].unique().tolist()}")
print(f"Referral Sources: {df_clean['ReferralSource'].unique().tolist()}")

print("\n4️⃣ BASIC STATISTICS:")
df_clean.describe()

📊 EXPLORE YOUR CLEAN DATASET
============================================================

1️⃣ FIRST 5 ROWS:

2️⃣ DATASET INFO:
<class 'pandas.core.frame.DataFrame'>
Index: 1189 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1189 non-null   object
 1   Date             1189 non-null   object
 2   CustomerID       1189 non-null   object
 3   Product          1189 non-null   object
 4   Quantity         1189 non-null   int64
 5   UnitPrice        1189 non-null   float64
 6   ShippingAddress  1189 non-null   object
 7   PaymentMethod    1189 non-null   object
 8   OrderStatus      1189 non-null   object
 9   TrackingNumber   1189 non-null   object
 10  ItemsInCart      1189 non-null   int64
 11  CouponCode       1189 non-null   object
 12  ReferralSource   1189 non-null   object
 13  TotalPrice       1189 non-null   float64
dtypes: float64(2), int64(2), object(10)
memory usage: 139.3+ KB

3️⃣ UNIQUE VALUES IN KEY COLUMNS:
Products: ['Monitor', 'Phone', 'Tablet', 'Chair', 'Printer', 'Laptop', 'Desk']
Payment Methods: ['Debit Card', 'Online', 'Credit Card', 'Gift Card', 'Cash']
Order Statuses: ['Shipped', 'Cancelled', 'Returned', 'Delivered', 'Pending']
Referral Sources: ['Instagram', 'Referral', 'Email', 'Facebook', 'Google']

4️⃣ BASIC STATISTICS:

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1189.000000  1189.000000  1189.000000  1189.000000
mean      2.941968   356.890917     5.482759  1053.708419
std       1.409144   196.733607     2.282066   818.011392
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   187.880000     4.000000   410.600000
50%       3.000000   364.420000     5.000000   824.250000
75%       4.000000   521.400000     7.000000  1580.350000
max       5.000000   699.930000    10.000000  3456.400000